import type { UnitType } from '../types'

export interface CatalogItem {
  id: string
  barcode: string
  name_en: string
  name_fa: string
  name_ps: string
  unit: UnitType
  category: string
  suggested_cost: number
  suggested_price: number
  default_stock: number
}

/**
 * Standard Afghan commodities catalog.
 * Provides pre-configured, trilingual commodities with realistic market pricing (AFN),
 * units, barcodes, and inventory defaults.
 */
export const COMMON_CATALOG_ITEMS: CatalogItem[] = [
  {
    id: 'oil',
    barcode: '1001',
    name_en: 'Cooking Oil',
    name_fa: 'روغن خوراکی',
    name_ps: 'غوړي',
    unit: 'litre',
    category: 'Groceries',
    suggested_cost: 110,
    suggested_price: 130,
    default_stock: 45,
  },
  {
    id: 'ghee',
    barcode: '1002',
    name_en: 'Vegetable Ghee',
    name_fa: 'روغن نباتی',
    name_ps: 'نباتی غوړي',
    unit: 'kg',
    category: 'Groceries',
    suggested_cost: 130,
    suggested_price: 150,
    default_stock: 35,
  },
  {
    id: 'rice',
    barcode: '1003',
    name_en: 'Basmati Rice',
    name_fa: 'برنج باریک سیلای',
    name_ps: 'سیله وریژې',
    unit: 'kg',
    category: 'Grains',
    suggested_cost: 90,
    suggested_price: 115,
    default_stock: 60,
  },
  {
    id: 'sugar',
    barcode: '1004',
    name_en: 'White Sugar',
    name_fa: 'بوره سفید',
    name_ps: 'سپینه بوره',
    unit: 'kg',
    category: 'Groceries',
    suggested_cost: 45,
    suggested_price: 55,
    default_stock: 80,
  },
  {
    id: 'flour',
    barcode: '1005',
    name_en: 'Wheat Flour',
    name_fa: 'آرد گندم',
    name_ps: 'د غنمو اوړه',
    unit: 'kg',
    category: 'Grains',
    suggested_cost: 32,
    suggested_price: 40,
    default_stock: 120,
  },
  {
    id: 'tea-green',
    barcode: '1006',
    name_en: 'Green Tea',
    name_fa: 'چای سبز',
    name_ps: 'شنه چای',
    unit: 'kg',
    category: 'Beverages',
    suggested_cost: 280,
    suggested_price: 350,
    default_stock: 25,
  },
  {
    id: 'tea-black',
    barcode: '1007',
    name_en: 'Black Tea',
    name_fa: 'چای سیاه',
    name_ps: 'توره چای',
    unit: 'kg',
    category: 'Beverages',
    suggested_cost: 320,
    suggested_price: 400,
    default_stock: 20,
  },
  {
    id: 'milk',
    barcode: '1008',
    name_en: 'Fresh Milk',
    name_fa: 'شیر تازه',
    name_ps: 'تازه شیدې',
    unit: 'litre',
    category: 'Dairy',
    suggested_cost: 50,
    suggested_price: 65,
    default_stock: 40,
  },
  {
    id: 'powder-milk',
    barcode: '1009',
    name_en: 'Dry Milk Powder',
    name_fa: 'شیر خشک',
    name_ps: 'وچې شیدې',
    unit: 'pack',
    category: 'Dairy',
    suggested_cost: 210,
    suggested_price: 260,
    default_stock: 30,
  },
  {
    id: 'eggs',
    barcode: '1010',
    name_en: 'Farm Eggs',
    name_fa: 'تخم مرغ',
    name_ps: 'هګۍ',
    unit: 'pcs',
    category: 'Dairy',
    suggested_cost: 7,
    suggested_price: 10,
    default_stock: 180,
  },
  {
    id: 'salt',
    barcode: '1011',
    name_en: 'Table Salt',
    name_fa: 'نمک طعام',
    name_ps: 'مالګه',
    unit: 'kg',
    category: 'Spices',
    suggested_cost: 15,
    suggested_price: 25,
    default_stock: 50,
  },
  {
    id: 'lentils',
    barcode: '1012',
    name_en: 'Red Lentils (Dal)',
    name_fa: 'دال سرخ / عدس',
    name_ps: 'سرخ دال',
    unit: 'kg',
    category: 'Legumes',
    suggested_cost: 80,
    suggested_price: 100,
    default_stock: 40,
  },
  {
    id: 'chickpeas',
    barcode: '1013',
    name_en: 'White Chickpeas',
    name_fa: 'نخود سفید',
    name_ps: 'سپین نخود',
    unit: 'kg',
    category: 'Legumes',
    suggested_cost: 95,
    suggested_price: 120,
    default_stock: 40,
  },
  {
    id: 'beans-kidney',
    barcode: '1014',
    name_en: 'Red Kidney Beans',
    name_fa: 'لوبیا سرخ',
    name_ps: 'سره لوبیا',
    unit: 'kg',
    category: 'Legumes',
    suggested_cost: 110,
    suggested_price: 135,
    default_stock: 35,
  },
  {
    id: 'tomato-paste',
    barcode: '1015',
    name_en: 'Tomato Paste',
    name_fa: 'رب رومی',
    name_ps: 'د رومي بانجانو رب',
    unit: 'pcs',
    category: 'Canned Goods',
    suggested_cost: 65,
    suggested_price: 80,
    default_stock: 50,
  },
  {
    id: 'detergent',
    barcode: '1016',
    name_en: 'Washing Powder',
    name_fa: 'پودر لباسشویی',
    name_ps: 'د کالیو پریمنځلو پوډر',
    unit: 'pack',
    category: 'Cleaning',
    suggested_cost: 85,
    suggested_price: 110,
    default_stock: 40,
  },
  {
    id: 'dish-soap',
    barcode: '1017',
    name_en: 'Dishwashing Liquid',
    name_fa: 'مایع ظرفشویی',
    name_ps: 'د لوښو مینځلو مایع',
    unit: 'litre',
    category: 'Cleaning',
    suggested_cost: 60,
    suggested_price: 75,
    default_stock: 30,
  },
  {
    id: 'soap',
    barcode: '1018',
    name_en: 'Bath Soap',
    name_fa: 'صابون دست و صورت',
    name_ps: 'صابون',
    unit: 'pcs',
    category: 'Personal Care',
    suggested_cost: 30,
    suggested_price: 40,
    default_stock: 60,
  },
  {
    id: 'shampoo',
    barcode: '1019',
    name_en: 'Hair Shampoo',
    name_fa: 'شامپو موی سر',
    name_ps: 'شامپو',
    unit: 'pcs',
    category: 'Personal Care',
    suggested_cost: 90,
    suggested_price: 120,
    default_stock: 25,
  },
  {
    id: 'water',
    barcode: '1020',
    name_en: 'Mineral Water',
    name_fa: 'آب معدنی',
    name_ps: 'معدني اوبه',
    unit: 'pcs',
    category: 'Beverages',
    suggested_cost: 15,
    suggested_price: 20,
    default_stock: 100,
  },
  {
    id: 'biscuits',
    barcode: '1021',
    name_en: 'Sweet Biscuits',
    name_fa: 'بیسکویت',
    name_ps: 'بیسکویټ',
    unit: 'pack',
    category: 'Snacks',
    suggested_cost: 20,
    suggested_price: 30,
    default_stock: 80,
  },
  {
    id: 'macaroni',
    barcode: '1022',
    name_en: 'Macaroni / Pasta',
    name_fa: 'ماکارونی',
    name_ps: 'ماکروني',
    unit: 'pack',
    category: 'Grains',
    suggested_cost: 40,
    suggested_price: 55,
    default_stock: 50,
  },
  {
    id: 'potatoes',
    barcode: '1023',
    name_en: 'Fresh Potatoes',
    name_fa: 'کچالو',
    name_ps: 'کچالو',
    unit: 'kg',
    category: 'Vegetables',
    suggested_cost: 25,
    suggested_price: 35,
    default_stock: 70,
  },
  {
    id: 'onions',
    barcode: '1024',
    name_en: 'Dry Onions',
    name_fa: 'پیاز خشک',
    name_ps: 'پیاز',
    unit: 'kg',
    category: 'Vegetables',
    suggested_cost: 20,
    suggested_price: 30,
    default_stock: 60,
  },
  {
    id: 'soda',
    barcode: '1025',
    name_en: 'Soft Drink (Cola)',
    name_fa: 'نوشابه گازدار',
    name_ps: 'ګاز لرونکې څښاک',
    unit: 'pcs',
    category: 'Beverages',
    suggested_cost: 25,
    suggested_price: 35,
    default_stock: 90,
  },
  {
    id: 'juice',
    barcode: '1026',
    name_en: 'Natural Fruit Juice',
    name_fa: 'آب میوه طبیعی',
    name_ps: 'د میوې اوبه',
    unit: 'pcs',
    category: 'Beverages',
    suggested_cost: 30,
    suggested_price: 45,
    default_stock: 50,
  },
  {
    id: 'matches',
    barcode: '1027',
    name_en: 'Matchbox',
    name_fa: 'گوگرد / کبریت',
    name_ps: 'اورلګیت',
    unit: 'pack',
    category: 'Household',
    suggested_cost: 5,
    suggested_price: 10,
    default_stock: 100,
  },
  {
    id: 'tissues',
    barcode: '1028',
    name_en: 'Facial Tissues',
    name_fa: 'دستمال کاغذی',
    name_ps: 'کاغذي رومال',
    unit: 'pack',
    category: 'Household',
    suggested_cost: 35,
    suggested_price: 50,
    default_stock: 40,
  },
]

/**
 * Searches the catalog by query against English, Persian, Pashto, barcode, or category.
 */
export function findCatalogItemByQuery(query: string): CatalogItem | undefined {
  if (!query || !query.trim()) return undefined
  const q = query.trim().toLowerCase()

  return COMMON_CATALOG_ITEMS.find(
    (it) =>
      it.id.toLowerCase() === q ||
      it.barcode.toLowerCase() === q ||
      it.name_en.toLowerCase().includes(q) ||
      it.name_fa.toLowerCase().includes(q) ||
      it.name_ps.toLowerCase().includes(q) ||
      it.category.toLowerCase().includes(q)
  )
}
