/**
 * src/main/db/defaultCatalog.ts
 *
 * Seed commodities for SQLite catalog_items and initial products tables.
 * Stored directly in SQLite DB on initialization.
 */

import type { DbCatalogItem } from './catalog'

export const DEFAULT_CATALOG_ITEMS: DbCatalogItem[] = [
  // 1. Grains, Flours & Bakery
  {
    id: 'flour-wheat',
    barcode: '1001',
    name_en: 'Wheat Flour',
    name_fa: 'آرد گندم',
    name_ps: 'د غنمو اوړه',
    unit: 'kg',
    category: 'Grains',
    suggested_cost: 32,
    suggested_price: 40,
    default_stock: 150,
  },
  {
    id: 'flour-kazakh',
    barcode: '1002',
    name_en: 'Kazakh White Flour',
    name_fa: 'آرد سفید قزاقی',
    name_ps: 'سپین قزاقي اوړه',
    unit: 'kg',
    category: 'Grains',
    suggested_cost: 36,
    suggested_price: 45,
    default_stock: 120,
  },
  {
    id: 'rice-basmati',
    barcode: '1003',
    name_en: 'Basmati Rice',
    name_fa: 'برنج باریک سیلای',
    name_ps: 'سیله وریژې',
    unit: 'kg',
    category: 'Grains',
    suggested_cost: 90,
    suggested_price: 115,
    default_stock: 80,
  },
  {
    id: 'rice-sela-super',
    barcode: '1004',
    name_en: 'Super Sela Rice',
    name_fa: 'برنج سوپر سیله اول',
    name_ps: 'لومړۍ درجه سوپر سیله وریژې',
    unit: 'kg',
    category: 'Grains',
    suggested_cost: 110,
    suggested_price: 135,
    default_stock: 60,
  },
  {
    id: 'rice-shola',
    barcode: '1005',
    name_en: 'Short Grain Rice',
    name_fa: 'برنج گرده / لک',
    name_ps: 'ګرده وریژې',
    unit: 'kg',
    category: 'Grains',
    suggested_cost: 65,
    suggested_price: 80,
    default_stock: 70,
  },
  {
    id: 'macaroni',
    barcode: '1006',
    name_en: 'Macaroni Pasta',
    name_fa: 'ماکارونی رشته‌ای',
    name_ps: 'ماکروني',
    unit: 'pack',
    category: 'Grains',
    suggested_cost: 40,
    suggested_price: 55,
    default_stock: 60,
  },
  {
    id: 'vermicelli',
    barcode: '1007',
    name_en: 'Vermicelli Seviyan',
    name_fa: 'سویا رشته / ورمیشل',
    name_ps: 'سوې / ورمیشل',
    unit: 'pack',
    category: 'Grains',
    suggested_cost: 30,
    suggested_price: 45,
    default_stock: 50,
  },
  {
    id: 'oats',
    barcode: '1008',
    name_en: 'Rolled Oats',
    name_fa: 'جو دو سر پرک',
    name_ps: 'اوربشې',
    unit: 'pack',
    category: 'Grains',
    suggested_cost: 85,
    suggested_price: 110,
    default_stock: 30,
  },

  // 2. Cooking Oils & Fats
  {
    id: 'oil-cooking',
    barcode: '1009',
    name_en: 'Cooking Oil',
    name_fa: 'روغن مایع خوراکی',
    name_ps: 'د پخلي مایع غوړي',
    unit: 'litre',
    category: 'Oils',
    suggested_cost: 110,
    suggested_price: 130,
    default_stock: 60,
  },
  {
    id: 'oil-sunflower',
    barcode: '1010',
    name_en: 'Sunflower Oil',
    name_fa: 'روغن آفتابگردان',
    name_ps: 'د لمرګلي غوړي',
    unit: 'litre',
    category: 'Oils',
    suggested_cost: 120,
    suggested_price: 145,
    default_stock: 45,
  },
  {
    id: 'ghee-vegetable',
    barcode: '1011',
    name_en: 'Vegetable Ghee',
    name_fa: 'روغن نباتی جامد',
    name_ps: 'نباتی غوړي',
    unit: 'kg',
    category: 'Oils',
    suggested_cost: 130,
    suggested_price: 155,
    default_stock: 40,
  },
  {
    id: 'oil-olive',
    barcode: '1012',
    name_en: 'Extra Virgin Olive Oil',
    name_fa: 'روغن زیتون خالص',
    name_ps: 'د زیتون خالص غوړي',
    unit: 'litre',
    category: 'Oils',
    suggested_cost: 380,
    suggested_price: 480,
    default_stock: 20,
  },

  // 3. Sugars & Sweeteners
  {
    id: 'sugar-white',
    barcode: '1013',
    name_en: 'White Sugar',
    name_fa: 'بوره سفید',
    name_ps: 'سپینه بوره',
    unit: 'kg',
    category: 'Groceries',
    suggested_cost: 45,
    suggested_price: 55,
    default_stock: 120,
  },
  {
    id: 'sugar-brown',
    barcode: '1014',
    name_en: 'Brown Sugar',
    name_fa: 'بوره نصواری',
    name_ps: 'نسواري بوره',
    unit: 'kg',
    category: 'Groceries',
    suggested_cost: 65,
    suggested_price: 85,
    default_stock: 35,
  },
  {
    id: 'crystal-rock-sugar',
    barcode: '1015',
    name_en: 'Crystal Rock Sugar (Nabat)',
    name_fa: 'شاخه نبات زعفرانی',
    name_ps: 'زعفراني نبات',
    unit: 'kg',
    category: 'Groceries',
    suggested_cost: 95,
    suggested_price: 130,
    default_stock: 30,
  },
  {
    id: 'honey-natural',
    barcode: '1016',
    name_en: 'Pure Natural Honey',
    name_fa: 'عسل طبیعی کوهی',
    name_ps: 'طبیعي شات',
    unit: 'kg',
    category: 'Groceries',
    suggested_cost: 450,
    suggested_price: 600,
    default_stock: 15,
  },

  // 4. Teas, Coffee & Beverages
  {
    id: 'tea-green',
    barcode: '1017',
    name_en: 'Green Tea',
    name_fa: 'چای سبز اعلی',
    name_ps: 'شنه چای',
    unit: 'kg',
    category: 'Beverages',
    suggested_cost: 280,
    suggested_price: 350,
    default_stock: 30,
  },
  {
    id: 'tea-black',
    barcode: '1018',
    name_en: 'Black Tea',
    name_fa: 'چای سیاه معطر',
    name_ps: 'توره چای',
    unit: 'kg',
    category: 'Beverages',
    suggested_cost: 320,
    suggested_price: 400,
    default_stock: 25,
  },
  {
    id: 'tea-cardamom',
    barcode: '1019',
    name_en: 'Cardamom Green Tea',
    name_fa: 'چای سبز هل‌دار',
    name_ps: 'د هېل شنه چای',
    unit: 'kg',
    category: 'Beverages',
    suggested_cost: 340,
    suggested_price: 420,
    default_stock: 20,
  },
  {
    id: 'coffee-instant',
    barcode: '1020',
    name_en: 'Instant Coffee Jar',
    name_fa: 'قهوه فوری',
    name_ps: 'چټکه قهوه',
    unit: 'pcs',
    category: 'Beverages',
    suggested_cost: 220,
    suggested_price: 280,
    default_stock: 25,
  },
  {
    id: 'water-mineral',
    barcode: '1021',
    name_en: 'Mineral Water 1.5L',
    name_fa: 'آب معدنی ۱.۵ لیتره',
    name_ps: '۱.۵ لیتره معدني اوبه',
    unit: 'pcs',
    category: 'Beverages',
    suggested_cost: 15,
    suggested_price: 20,
    default_stock: 120,
  },
  {
    id: 'soda-cola',
    barcode: '1022',
    name_en: 'Cola Soft Drink Can',
    name_fa: 'نوشابه کولا',
    name_ps: 'کولا څښاک',
    unit: 'pcs',
    category: 'Beverages',
    suggested_cost: 25,
    suggested_price: 35,
    default_stock: 96,
  },
  {
    id: 'soda-orange',
    barcode: '1023',
    name_en: 'Orange Soda Can',
    name_fa: 'نوشابه گازدار نارنجی',
    name_ps: 'نارنجي څښاک',
    unit: 'pcs',
    category: 'Beverages',
    suggested_cost: 25,
    suggested_price: 35,
    default_stock: 72,
  },
  {
    id: 'juice-mango',
    barcode: '1024',
    name_en: 'Natural Fruit Juice',
    name_fa: 'آب میوه طبیعی پاکتی',
    name_ps: 'د میوې پاکټي اوبه',
    unit: 'pcs',
    category: 'Beverages',
    suggested_cost: 30,
    suggested_price: 45,
    default_stock: 60,
  },
  {
    id: 'energy-drink',
    barcode: '1025',
    name_en: 'Energy Drink Can',
    name_fa: 'نوشابه انرژی‌زا',
    name_ps: 'انرژي لرونکی څښاک',
    unit: 'pcs',
    category: 'Beverages',
    suggested_cost: 45,
    suggested_price: 65,
    default_stock: 48,
  },

  // 5. Dairy & Eggs
  {
    id: 'milk-fresh',
    barcode: '1026',
    name_en: 'Fresh Whole Milk',
    name_fa: 'شیر تازه پاستوریزه',
    name_ps: 'تازه شیدې',
    unit: 'litre',
    category: 'Dairy',
    suggested_cost: 50,
    suggested_price: 65,
    default_stock: 40,
  },
  {
    id: 'milk-powder',
    barcode: '1027',
    name_en: 'Dry Milk Powder (Nido)',
    name_fa: 'شیر خشک نیدو',
    name_ps: 'وچې شیدې نیدو',
    unit: 'pack',
    category: 'Dairy',
    suggested_cost: 280,
    suggested_price: 350,
    default_stock: 30,
  },
  {
    id: 'eggs-farm',
    barcode: '1028',
    name_en: 'Fresh Farm Eggs',
    name_fa: 'تخم مرغ تازه فارمی',
    name_ps: 'فارمي هګۍ',
    unit: 'pcs',
    category: 'Dairy',
    suggested_cost: 7,
    suggested_price: 10,
    default_stock: 240,
  },
  {
    id: 'yogurt-plain',
    barcode: '1029',
    name_en: 'Plain Yogurt Tub',
    name_fa: 'ماست ساده تازه',
    name_ps: 'ساده مستې',
    unit: 'kg',
    category: 'Dairy',
    suggested_cost: 45,
    suggested_price: 60,
    default_stock: 30,
  },
  {
    id: 'butter-fresh',
    barcode: '1030',
    name_en: 'Dairy Butter',
    name_fa: 'مسکه تازه حیوانی',
    name_ps: 'تازه کوچ',
    unit: 'kg',
    category: 'Dairy',
    suggested_cost: 320,
    suggested_price: 400,
    default_stock: 20,
  },
  {
    id: 'cheese-white',
    barcode: '1031',
    name_en: 'White Feta Cheese',
    name_fa: 'پنیر سفید صبحانه',
    name_ps: 'سپینه پنیر',
    unit: 'kg',
    category: 'Dairy',
    suggested_cost: 160,
    suggested_price: 210,
    default_stock: 25,
  },
  {
    id: 'cream-qaimaq',
    barcode: '1032',
    name_en: 'Fresh Cream (Qaimaq)',
    name_fa: 'قیماق تازه',
    name_ps: 'تازه قیماق',
    unit: 'pack',
    category: 'Dairy',
    suggested_cost: 70,
    suggested_price: 95,
    default_stock: 25,
  },

  // 6. Pulses & Legumes
  {
    id: 'lentils-red',
    barcode: '1033',
    name_en: 'Red Lentils (Masoor Dal)',
    name_fa: 'دال سرخ / عدس سرخ',
    name_ps: 'سرخ دال',
    unit: 'kg',
    category: 'Legumes',
    suggested_cost: 80,
    suggested_price: 100,
    default_stock: 50,
  },
  {
    id: 'lentils-yellow',
    barcode: '1034',
    name_en: 'Yellow Split Peas (Chana Dal)',
    name_fa: 'دال نخود زرد',
    name_ps: 'ژېړ دال',
    unit: 'kg',
    category: 'Legumes',
    suggested_cost: 85,
    suggested_price: 105,
    default_stock: 45,
  },
  {
    id: 'chickpeas-white',
    barcode: '1035',
    name_en: 'White Chickpeas',
    name_fa: 'نخود سفید اعلا',
    name_ps: 'سپین نخود',
    unit: 'kg',
    category: 'Legumes',
    suggested_cost: 95,
    suggested_price: 120,
    default_stock: 45,
  },
  {
    id: 'beans-kidney-red',
    barcode: '1036',
    name_en: 'Red Kidney Beans',
    name_fa: 'لوبیا سرخ کابل',
    name_ps: 'سره لوبیا',
    unit: 'kg',
    category: 'Legumes',
    suggested_cost: 110,
    suggested_price: 135,
    default_stock: 40,
  },
  {
    id: 'beans-white',
    barcode: '1037',
    name_en: 'White Navy Beans',
    name_fa: 'لوبیا سفید',
    name_ps: 'سپینه لوبیا',
    unit: 'kg',
    category: 'Legumes',
    suggested_cost: 105,
    suggested_price: 130,
    default_stock: 40,
  },
  {
    id: 'mung-beans',
    barcode: '1038',
    name_en: 'Green Mung Beans',
    name_fa: 'ماش سبز وطنی',
    name_ps: 'شین ماش',
    unit: 'kg',
    category: 'Legumes',
    suggested_cost: 75,
    suggested_price: 95,
    default_stock: 35,
  },

  // 7. Spices, Salt & Condiments
  {
    id: 'salt-table',
    barcode: '1039',
    name_en: 'Iodized Table Salt',
    name_fa: 'نمک طعام یددار',
    name_ps: 'د خوړو مالګه',
    unit: 'kg',
    category: 'Spices',
    suggested_cost: 15,
    suggested_price: 25,
    default_stock: 60,
  },
  {
    id: 'tomato-paste-can',
    barcode: '1040',
    name_en: 'Tomato Paste Can',
    name_fa: 'رب رومی قوطی',
    name_ps: 'د رومي بانجانو رب',
    unit: 'pcs',
    category: 'Canned Goods',
    suggested_cost: 65,
    suggested_price: 80,
    default_stock: 60,
  },
  {
    id: 'spice-turmeric',
    barcode: '1041',
    name_en: 'Turmeric Powder',
    name_fa: 'پودر زردچوبه خالص',
    name_ps: 'د کورکمنو پوډر',
    unit: 'kg',
    category: 'Spices',
    suggested_cost: 140,
    suggested_price: 180,
    default_stock: 25,
  },
  {
    id: 'spice-black-pepper',
    barcode: '1042',
    name_en: 'Black Pepper Ground',
    name_fa: 'مرچ سیاه کوبیده',
    name_ps: 'توره مرچ',
    unit: 'kg',
    category: 'Spices',
    suggested_cost: 320,
    suggested_price: 420,
    default_stock: 20,
  },
  {
    id: 'spice-red-chili',
    barcode: '1043',
    name_en: 'Red Chili Powder',
    name_fa: 'مرچ سرخ تند',
    name_ps: 'توده سره مرچ',
    unit: 'kg',
    category: 'Spices',
    suggested_cost: 180,
    suggested_price: 230,
    default_stock: 25,
  },
  {
    id: 'spice-cumin',
    barcode: '1044',
    name_en: 'Cumin Seeds (Zeera)',
    name_fa: 'زیره سیاه وطنی',
    name_ps: 'توره زیره',
    unit: 'kg',
    category: 'Spices',
    suggested_cost: 480,
    suggested_price: 600,
    default_stock: 15,
  },
  {
    id: 'spice-cardamom',
    barcode: '1045',
    name_en: 'Green Cardamom (Hel)',
    name_fa: 'هل سبز دانه درشت',
    name_ps: 'شین هېل',
    unit: 'kg',
    category: 'Spices',
    suggested_cost: 1200,
    suggested_price: 1500,
    default_stock: 10,
  },
  {
    id: 'spice-cinnamon',
    barcode: '1046',
    name_en: 'Cinnamon Sticks',
    name_fa: 'چوب دارچین',
    name_ps: 'دارچیني لرګی',
    unit: 'kg',
    category: 'Spices',
    suggested_cost: 260,
    suggested_price: 340,
    default_stock: 15,
  },
  {
    id: 'sauce-mayo',
    barcode: '1047',
    name_en: 'Mayonnaise Jar',
    name_fa: 'سس مایونز',
    name_ps: 'مایونیز ساس',
    unit: 'pcs',
    category: 'Groceries',
    suggested_cost: 85,
    suggested_price: 115,
    default_stock: 35,
  },
  {
    id: 'sauce-ketchup',
    barcode: '1048',
    name_en: 'Tomato Ketchup Bottle',
    name_fa: 'سس کچاپ رومی',
    name_ps: 'کیچپ ساس',
    unit: 'pcs',
    category: 'Groceries',
    suggested_cost: 65,
    suggested_price: 90,
    default_stock: 40,
  },

  // 8. Fresh Produce & Vegetables
  {
    id: 'potato',
    barcode: '1049',
    name_en: 'Fresh Potatoes',
    name_fa: 'کچالو تازه بامیان',
    name_ps: 'تازه کچالو',
    unit: 'kg',
    category: 'Produce',
    suggested_cost: 25,
    suggested_price: 35,
    default_stock: 150,
  },
  {
    id: 'onion',
    barcode: '1050',
    name_en: 'Dry Onions',
    name_fa: 'پیاز زرد خشک',
    name_ps: 'پیاز',
    unit: 'kg',
    category: 'Produce',
    suggested_cost: 20,
    suggested_price: 30,
    default_stock: 120,
  },
  {
    id: 'garlic',
    barcode: '1051',
    name_en: 'Fresh Garlic',
    name_fa: 'سیر تازه',
    name_ps: 'اوږه',
    unit: 'kg',
    category: 'Produce',
    suggested_cost: 70,
    suggested_price: 95,
    default_stock: 40,
  },
  {
    id: 'tomatoes-fresh',
    barcode: '1052',
    name_en: 'Fresh Tomatoes',
    name_fa: 'بادنجان رومی تازه',
    name_ps: 'رومي بانجان',
    unit: 'kg',
    category: 'Produce',
    suggested_cost: 35,
    suggested_price: 50,
    default_stock: 80,
  },

  // 9. Cleaning, Detergents & Household
  {
    id: 'detergent-powder',
    barcode: '1053',
    name_en: 'Washing Machine Powder',
    name_fa: 'پودر لباسشویی دستی و ماشینی',
    name_ps: 'د کالیو پریمنځلو پوډر',
    unit: 'pack',
    category: 'Cleaning',
    suggested_cost: 85,
    suggested_price: 110,
    default_stock: 50,
  },
  {
    id: 'dish-liquid',
    barcode: '1054',
    name_en: 'Dishwashing Liquid',
    name_fa: 'مایع ظرفشویی',
    name_ps: 'د لوښو مینځلو مایع',
    unit: 'litre',
    category: 'Cleaning',
    suggested_cost: 60,
    suggested_price: 75,
    default_stock: 40,
  },
  {
    id: 'soap-bath',
    barcode: '1055',
    name_en: 'Bath Beauty Soap',
    name_fa: 'صابون دست و صورت معطر',
    name_ps: 'د لاس صابون',
    unit: 'pcs',
    category: 'Personal Care',
    suggested_cost: 30,
    suggested_price: 40,
    default_stock: 75,
  },
  {
    id: 'shampoo-hair',
    barcode: '1056',
    name_en: 'Hair Shampoo Bottle',
    name_fa: 'شامپو موی سر تقویت‌کننده',
    name_ps: 'د ویښتانو شامپو',
    unit: 'pcs',
    category: 'Personal Care',
    suggested_cost: 90,
    suggested_price: 120,
    default_stock: 35,
  },
  {
    id: 'toothpaste',
    barcode: '1057',
    name_en: 'Fluoride Toothpaste',
    name_fa: 'خمیر دندان فلوراید',
    name_ps: 'د غاښونو کریم',
    unit: 'pcs',
    category: 'Personal Care',
    suggested_cost: 45,
    suggested_price: 65,
    default_stock: 45,
  },
  {
    id: 'bleach',
    barcode: '1058',
    name_en: 'Bleach / Whitener Liquid',
    name_fa: 'مایع سفیدکننده (وایتکس)',
    name_ps: 'وایټکس مایع',
    unit: 'litre',
    category: 'Cleaning',
    suggested_cost: 40,
    suggested_price: 55,
    default_stock: 30,
  },
  {
    id: 'tissues-box',
    barcode: '1059',
    name_en: 'Facial Tissues Box',
    name_fa: 'دستمال کاغذی جعبه‌ای',
    name_ps: 'کاغذي رومال بکس',
    unit: 'pack',
    category: 'Household',
    suggested_cost: 35,
    suggested_price: 50,
    default_stock: 60,
  },
  {
    id: 'trash-bags',
    barcode: '1060',
    name_en: 'Heavy Duty Trash Bags',
    name_fa: 'پلاستیک زباله ضخیم',
    name_ps: 'د کثافاتو کڅوړه',
    unit: 'pack',
    category: 'Household',
    suggested_cost: 50,
    suggested_price: 70,
    default_stock: 40,
  },
  {
    id: 'matches-pack',
    barcode: '1061',
    name_en: 'Safety Matches Bundle',
    name_fa: 'بسته گوگرد / کبریت',
    name_ps: 'اورلګیت',
    unit: 'pack',
    category: 'Household',
    suggested_cost: 15,
    suggested_price: 25,
    default_stock: 80,
  },

  // 10. Snacks & Confectionery
  {
    id: 'biscuits-sweet',
    barcode: '1062',
    name_en: 'Sweet Cream Biscuits',
    name_fa: 'بیسکویت کرم‌دار شیرین',
    name_ps: 'کریم لرونکی بیسکویټ',
    unit: 'pack',
    category: 'Snacks',
    suggested_cost: 20,
    suggested_price: 30,
    default_stock: 100,
  },
  {
    id: 'chocolate-bar',
    barcode: '1063',
    name_en: 'Milk Chocolate Bar',
    name_fa: 'چاکلیت شیری',
    name_ps: 'د شیدو چاکلیټ',
    unit: 'pcs',
    category: 'Snacks',
    suggested_cost: 25,
    suggested_price: 40,
    default_stock: 80,
  },
  {
    id: 'potato-chips',
    barcode: '1064',
    name_en: 'Crispy Potato Chips',
    name_fa: 'چیپس کچالو نمکی',
    name_ps: 'کچالو چپس',
    unit: 'pack',
    category: 'Snacks',
    suggested_cost: 15,
    suggested_price: 25,
    default_stock: 90,
  },
]
